---
- name: import global variables
  include_vars:
    dir: "{{ inventory_dir }}/group_vars/"

- name: import Vault-encrypted variables with API tokens and Telegram chat IDs
  include_vars: vault.yml

- name: add nodejs third-party repository
  package:
    state: present
    name: https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm

- name: add yarn third-party repository
  get_url:
    dest: "/etc/yum.repos.d/"
    url: "https://dl.yarnpkg.com/rpm/yarn.repo"
    setype: system_conf_t
    seuser: system_u

- name: install nodejs and yarn
  package:
    state: present
    name:
      - nodejs
      - yarn

- name: create system user for Teleirc bots
  user:
    name: teleirc
    comment: "system user to run RITlug/teleirc bots - do not use"
    system: yes
    home: "/usr/lib64/teleirc"
    create_home: no

- name: add target user to Teleirc admin group
  user:
    name: "{{ target_user }}"
    groups: teleirc
    append: yes

- name: create root directory for Teleirc bots
  file:
    state: directory
    path: "/usr/lib64/teleirc"
    mode: 0755
    owner: teleirc
    group: teleirc
    seuser: system_u

- name: git clone/pull RITlug/teleirc
  git:
    repo: "https://github.com/RITlug/teleirc.git"
    dest: "/usr/lib64/teleirc/{{ item.value.cn }}"
    version: "{{ item.value.version }}"
    force: yes
  loop: "{{ bots|dict2items }}"
  notify:
    - install build dependencies
    - install runtime dependencies with yarn
    - remove build dependencies
    - restart teleirc

- name: "set file permissions to teleirc:teleirc in /usr/lib64/teleirc/"
  file:
    state: directory
    recurse: yes
    path: "/usr/lib64/teleirc"
    owner: teleirc
    group: teleirc

- name: add templated configuration
  template:
    src: env
    dest: "/usr/lib64/teleirc/{{ item.value.cn }}/.env"
    mode: 0640
    owner: teleirc
    group: teleirc
    seuser: system_u
  loop: "{{ bots|dict2items }}"
  notify:
    - restart teleirc

- name: add templated systemd unit file
  template:
    src: teleirc.service
    dest: "/usr/lib/systemd/system/teleirc-{{ item.value.cn }}.service"
    mode: 0644
    seuser: system_u
    setype: systemd_unit_file_t
  loop: "{{ bots|dict2items }}"

- name: start/enable each Teleirc systemd unit file
  service:
    name: teleirc-{{ item.value.cn }}
    state: started
    enabled: yes
  loop: "{{ bots|dict2items }}"
