---
default_imgur_client_id: "{{ vault_default_imgur_client_id }}"
default_irc_server: chat.freenode.net
default_irc_nickserv_service: NickServ

bots:
  minecon_agents:
    cn: "minecon-agents"
    irc_blacklist: ""
    irc_bot_name: tg-mineconagents
    irc_channel: "#MineconAgents"
    irc_server: irc.esper.net
    irc_nickserv_service: "{{ default_irc_nickserv_service }}"
    irc_nickserv_password: "{{ vault_bots.minecon_agents.vault_irc_nickserv_password }}"
    teleirc_token: "{{ vault_bots.minecon_agents.vault_teleirc_token }}"
    teleirc_chat_id: "{{ vault_bots.minecon_agents.vault_teleirc_chat_id }}"
    imgur_client_id: "{{ default_imgur_client_id }}"

  musicbrainz:
    cn: "musicbrainz"
    irc_blacklist: ""
    irc_bot_name: tg-musicbrainz
    irc_channel: "#musicbrainz-telegram"
    irc_server: "{{ default_irc_server }}"
    irc_nickserv_service: "{{ default_irc_nickserv_service }}"
    irc_nickserv_password: "{{ vault_bots.musicbrainz.vault_irc_nickserv_password }}"
    teleirc_token: "{{ vault_bots.musicbrainz.vault_teleirc_token }}"
    teleirc_chat_id: "{{ vault_bots.musicbrainz.vault_teleirc_chat_id }}"
    imgur_client_id: "{{ default_imgur_client_id }}"

  rit_foss:
    cn: "rit-foss"
    irc_blacklist: "CowSayBot"
    irc_bot_name: tg-ritfoss
    irc_channel: "#rit-foss"
    irc_server: "{{ default_irc_server }}"
    irc_nickserv_service: "{{ default_irc_nickserv_service }}"
    irc_nickserv_password: "{{ vault_bots.rit_foss.vault_irc_nickserv_password }}"
    teleirc_token: "{{ vault_bots.rit_foss.vault_teleirc_token }}"
    teleirc_chat_id: "{{ vault_bots.rit_foss.vault_teleirc_chat_id }}"
    imgur_client_id: "{{ default_imgur_client_id }}"

  ritlug:
    cn: "ritlug"
    irc_blacklist: "CowSayBot"
    irc_bot_name: tg-ritlug
    irc_channel: "#ritlug"
    irc_server: "{{ default_irc_server }}"
    irc_nickserv_service: "{{ default_irc_nickserv_service }}"
    irc_nickserv_password: "{{ vault_bots.ritlug.vault_irc_nickserv_password }}"
    teleirc_token: "{{ vault_bots.ritlug.vault_teleirc_token }}"
    teleirc_chat_id: "{{ vault_bots.ritlug.vault_teleirc_chat_id }}"
    imgur_client_id: "{{ default_imgur_client_id }}"

  ritlug_teleirc:
    cn: "ritlug-teleirc"
    irc_blacklist: ""
    irc_bot_name: tg-teleirc
    irc_channel: "#ritlug-teleirc"
    irc_server: "{{ default_irc_server }}"
    irc_nickserv_service: "{{ default_irc_nickserv_service }}"
    irc_nickserv_password: "{{ vault_bots.ritlug_teleirc.vault_irc_nickserv_password }}"
    teleirc_token: "{{ vault_bots.ritlug_teleirc.vault_teleirc_token }}"
    teleirc_chat_id: "{{ vault_bots.ritlug_teleirc.vault_teleirc_chat_id }}"
    imgur_client_id: "{{ default_imgur_client_id }}"
