---
- name: install yum-cron
  package:
    state: latest
    name: yum-cron

- name: configure yum-cron (/etc/yum/yum-cron.conf)
  template:
    src: yum-cron.conf
    dest: /etc/yum/yum-cron.conf
  notify: restart yum-cron
