---
- name: install/upgrade firewalld and fail2ban
  package:
    state: latest
    name:
      - fail2ban
      - fail2ban-firewalld
      - firewalld

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
