---
- name: synchronize estrella
  hosts: estrella
  become: yes

  roles:
    - { role: base/centos-7, tags: base }
    - { role: firewalld, tags: firewalld }
    - { role: sshd, tags: sshd }
    - { role: yum-cron, tags: yum-cron }
